volumes:
  msdb:
  mytask_db:

networks:
    backend:

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: MyTask_API
    ports:
        - "8000:8081"
    build:
      context: .
      dockerfile: API/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend

  pgadmin:
    container_name: eatery-db-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@manage.task}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - msdb:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

  db:
    container_name: myTask-data
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=myTaskDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - mytask_db:/var/lib/postgresql/data